from .Biblioteca_crud import BibliotecaCRUD
from .Categoria_crud import CategoriaCRUD
from .Cliente_crud import ClienteCRUD
from .Material_Bibliografico_crud import MaterialBibliograficoCRUD
from .Prestamo_crud import PrestamoCRUD
from .Reserva_crud import ReservaCrud
from .Sancion_crud import SancionCRUD
from .Sede_crud import SedeCRUD
from .Usuario_crud import UsuarioCRUD