"""Mensaje de la migración

Revision ID: 0ddd24eaa6fd
Revises: 
Create Date: 2025-09-23 00:43:50.715934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddd24eaa6fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedes',
    sa.Column('id_sede', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], name='fk_sedes_usuario_crea', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], name='fk_sedes_usuario_edita', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('id_sede'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_sedes_id_sede'), 'sedes', ['id_sede'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('contraseña_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_table('bibliotecas',
    sa.Column('id_biblioteca', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_sede', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_sede'], ['sedes.id_sede'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_biblioteca'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias',
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.Column('id_biblioteca', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_biblioteca'], ['bibliotecas.id_biblioteca'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id_categoria'), 'categorias', ['id_categoria'], unique=False)
    op.create_table('clientes',
    sa.Column('codigo', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=80), nullable=True),
    sa.Column('detalle_tipo', sa.String(length=80), nullable=True),
    sa.Column('vetado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_biblioteca', sa.UUID(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_biblioteca'], ['bibliotecas.id_biblioteca'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_clientes_codigo'), 'clientes', ['codigo'], unique=False)
    op.create_table('materiales',
    sa.Column('id_material', sa.UUID(), nullable=False),
    sa.Column('id_biblioteca', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=80), nullable=True),
    sa.Column('autor', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_categoria', sa.UUID(), nullable=True),
    sa.Column('id_sede', sa.UUID(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_biblioteca'], ['bibliotecas.id_biblioteca'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_sede'], ['sedes.id_sede'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_index(op.f('ix_materiales_id_material'), 'materiales', ['id_material'], unique=False)
    op.create_table('sanciones',
    sa.Column('id_sancion', sa.UUID(), nullable=False),
    sa.Column('id_biblioteca', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.String(length=150), nullable=True),
    sa.Column('fecha_sancion', sa.Date(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cod_cliente', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cod_cliente'], ['clientes.codigo'], ),
    sa.ForeignKeyConstraint(['id_biblioteca'], ['bibliotecas.id_biblioteca'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sancion')
    )
    op.create_index(op.f('ix_sanciones_id_sancion'), 'sanciones', ['id_sancion'], unique=False)
    op.create_table('prestamos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_biblioteca', sa.UUID(), nullable=True),
    sa.Column('fecha_prestamo', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_material', sa.UUID(), nullable=True),
    sa.Column('cod_cliente', sa.UUID(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cod_cliente'], ['clientes.codigo'], ),
    sa.ForeignKeyConstraint(['id_biblioteca'], ['bibliotecas.id_biblioteca'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestamos_id'), 'prestamos', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id_reserva', sa.UUID(), nullable=False),
    sa.Column('id_biblioteca', sa.UUID(), nullable=True),
    sa.Column('fecha_reserva', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cod_cliente', sa.UUID(), nullable=True),
    sa.Column('id_material', sa.UUID(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=True),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cod_cliente'], ['clientes.codigo'], ),
    sa.ForeignKeyConstraint(['id_biblioteca'], ['bibliotecas.id_biblioteca'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index(op.f('ix_reservas_id_reserva'), 'reservas', ['id_reserva'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_id_reserva'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_prestamos_id'), table_name='prestamos')
    op.drop_table('prestamos')
    op.drop_index(op.f('ix_sanciones_id_sancion'), table_name='sanciones')
    op.drop_table('sanciones')
    op.drop_index(op.f('ix_materiales_id_material'), table_name='materiales')
    op.drop_table('materiales')
    op.drop_index(op.f('ix_clientes_codigo'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_id_categoria'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_table('bibliotecas')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sedes_id_sede'), table_name='sedes')
    op.drop_table('sedes')
    # ### end Alembic commands ###
